server:
  port: 9005
spring: 
  application:  
    name: ktc-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.190.130:3306/ktc_article?characterEncoding=UTF8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        format_sql: true	# 格式化sql
        show_sql: true		# 显示sql
  redis:
    password:
    jedis:
      pool:
        max-idle: 3
    host: 192.168.190.130
