server:
  port: 9009
spring:
  application:
    name: ktc_sms #微服名称
  rabbitmq:
    host: 192.168.190.130



aliyun:
  sms:
    accessKeyId: LTAIEswp7dItFR3n
    accessKeySecret: Hz80IUS5Y8uwdbE4tSj3rRzfb7cP2q
    template_code: SMS_173341708
    sign_name: 东方标准