server:
  port: 9003
spring: 
  application:  
    name: ktc-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.190.130:3306/ktc_qa?characterEncoding=UTF8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        format_sql: true	# 格式化sql
        show_sql: true		# 显示sql
