server:
  port: 9008
spring: 
  application:  
    name: ktc-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.190.130:3306/ktc_user?characterEncoding=UTF8
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        format_sql: true	# 格式化sql
        show_sql: true		# 显示sql
jwt:
  config:
    key: dfbz
    prefix: dfbz
